#!/bin/bash

set -e

SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PARENT_DIR="$(dirname "$SH_DIR")"
WORKING_DIR="$(basename "$PARENT_DIR")"


echo "$WORKING_DIR"


# Check for uncommitted changes
if [[ -n $(git status "$PARENT_DIR" -s) ]]; then
    echo "There are uncommitted changes. Exiting "$WORKING_DIR""
    exit 1
fi


if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0
fi


echo "$WORKING_DIR" Publishing...


docker run --rm \
    --name "$WORKING_DIR"-publish \
    -v "$PARENT_DIR":/opt/maven/ \
    -v "$PARENT_DIR"/.m2:/root/.m2/repository \
    -w /opt/maven \
    -e REPO_USERNAME=etidahouse \
    -e REPO_TOKEN=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 \
    maven:3.8.5-openjdk-17-slim \
    mvn clean deploy -s settings.xml
