#!/bin/bash
if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0
fi

WORKDING_DIR="$(pwd)"
CURRENT_DIR=$(basename $(pwd))

DOCKER_IMAGE=openjdk:17

CONTAINER_RUNTIME_NAME="$CURRENT_DIR-openjdk-17"

docker run -it --rm \
    --name "$CONTAINER_RUNTIME_NAME" \
    -v "$WORKDING_DIR"/target/spring-api-rest-ci.jar:/opt/spring-api-rest-ci.jar \
    -p 8085:8080 \
    $DOCKER_IMAGE java -jar /opt/spring-api-rest-ci.jar
